### PR TITLE
Add HubSpot to functions

### PR DESCRIPTION
**Pull request by williamspiro**
Adds HubSpot to the functions listing.

Please let me know if you have any copy, or other suggestions/questions. Thanks!

### CODE REVIEW

**Comment by chriscoyier** [comment]
cool

**Comment by williamspiro** [comment]
Thank you, @chriscoyier !

**Comment by TheWebTech** [comment]
This listing appears to have disappeared. It's not in Master.

Is there anything improper about the file that we should correct to get it re-submitted?

The only thing I can notice is that it seems maybe a new category was added and that this was intended to go in that CMS category and never got moved.

Thanks!

**Comment by chriscoyier** [comment]
It was put in Functions folder.

CleanShot 2021-01-21 at 11 52 25@2x

**Pull request merged**
