### PR TITLE
Update Cloud Functions “zeit”

### PR DESCRIPTION
**Pull request by saqibameen**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by chriscoyier** [comment]
Should probably change the file name here too, but not sure if that can be done via Netlify CMS.

**Comment by saqibameen** [comment]
@chriscoyier let me do it manually and update the PR. Btw love this project, came here after watching your talk! Thank you. 👌

**Comment by saqibameen** [comment]
File name updated to Vercel.

**Comment by chriscoyier** [comment]
hey thanks so much! Might as well change the file name and path of the logo too then just to be super consistent.

**Comment by saqibameen** [comment]
@chriscoyier just updated the path and name of the logo.

**Comment by chriscoyier** [comment]
Beautiful, thanks so much for all the effort here.

**Pull request merged**
