### PR TITLE
Add Begin to list. thanks!

### PR DESCRIPTION
**Pull request by pchinjr**
Really appreciate the effort put into this whole list. Wonderful choices all around no matter what cloud you're on!

### CODE REVIEW

**Comment by chriscoyier** [comment]
This isn't your problem... but I'm figuring out what I want to do here. In my head, Begin is a major service, but is in a similar boat to Netlify and Vercel. It does a lot, but isn't the actual provider. That's very clear with begin: stuff runs on AWS. So I think it makes sense to separate into sections the providers themselves with things that are built on top of the providers. Is there a name that makes sense for this category? Feels kinda like "Deployment" or "CI / CD", but that almost undersells it.

**Comment by pchinjr** [comment]
Hi Chris, thanks for responding. Begin is a CI/CD system for AWS Lambda functions. I totally agree that it's a new category of service. It wraps other services to support the deployment system. Vercel and Netlify also provide an abstraction to that deploy to AWS. There aren't clear lines for separating some of these, like Firebase. It's part of GCP, but it feels like a separate implementation of GCP Cloud Functions. Other clouds like IBM, Oracle, and Alibaba offer serverless functions as well, so the list can become pretty extensive. I'm happy to move Begin to the cloud functions section. I can also remove Apex from the list while I'm at it.

**Comment by chriscoyier** [comment]
Some initial thoughts:

- Combine Firebase in to GCP card.
- Instead of "Major Providers", change name to "Cloud Providers"
- Make a "CI / CD" section, and put Begin, Netlify, and Vercel in there (and maybe add some other classics like Circle CI)? And repeat the ones that mak in Hosting too?
- Is Apex dead? Doesn't say anything? https://apex.sh/up/ Maybe was just a name change, as I do see their URL on the site now is dead.

**Comment by chriscoyier** [comment]
Lettttts do this for now.

**Pull request merged**
