### PR TITLE
Update Major Providers “googlecloud”

### PR DESCRIPTION
**Pull request by NikilXYZ**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by chriscoyier** [comment]
thank you!

**Comment by NikilXYZ** [comment]
Yay!

Chris, Have you checked out TinaCMS?

I'm looking for something similar to Mobirise.com to pair with Gatsby so
that my marketing folks can directly edit the content on the page layout
itself (the ultimate WYSIWYG). Tina seems close but maybe there's something
else you know about as well?

Mobirise is an offline app that allows users to drag and drop sections
designed with Bootstrap and build a static website + shopping. Seriously
check it out - I think it's 100x better than Wix and ilk.
I thought it was gonna be crap but honestly it's pretty amazing.

*NIKIL RAGAV** | WHARTON BUSINESS | PENN ELECTRICAL ENGINEERING*

CEO inventXYZ <https://www.inventxyz.com/>

832.910.9645

**Comment by chriscoyier** [comment]
This is worth a look: https://css-tricks.com/video-screencasts/197-a-look-at-stackbit-and-stackbit-studio/

**Comment by NikilXYZ** [comment]
Oh thanks! It seems pretty close. Will be exploring more. Does this only
support deploying with netlify build tools?

*NIKIL RAGAV** | WHARTON BUSINESS | PENN ELECTRICAL ENGINEERING*

CEO inventXYZ <https://www.inventxyz.com/>

832.910.9645

**Pull request merged**
