### PR TITLE
Add Fixture to CMS solutions

### PR DESCRIPTION
**Pull request by madoublet**
Add Fixture to the CMS section.

### CODE REVIEW

**Comment by chriscoyier** [comment]
The Netlify build is failing here for some reason. Did it run locally OK?

**Comment by madoublet** [comment]
Sorry about that.  It did run locally.  But, I am not very familiar with netlify or gatsby.  I just ran

**Comment by madoublet** [comment]
... I ran "npm install" then "npm run develop" and it worked fine locally.  It automatically updated when I added the two files, so I just submitted the PR as is.

**Comment by chriscoyier** [comment]
Just having no luck here. SO WEIRD.

```
2:35:50 PM: error #85901 GRAPHQL
2:35:50 PM: There was an error in your GraphQL query:
2:35:50 PM: Unknown type "ImageSharpFixed".
2:35:50 PM: File: node_modules/gatsby-transformer-sharp/src/fragments.js:5:47
2:35:50 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
```

**Comment by madoublet** [comment]
Do you think it is related to the SVG?  I can resubmit it with a PNG.

**Comment by chriscoyier** [comment]
I thought MAYBE it was SVG, but there is a ton of other SVG in there that's no problem. I don't think it's you, it's something gone funky with Gatsby somehow.

**Comment by madoublet** [comment]
It looks like this is happening to others as well: https://github.com/gatsbyjs/gatsby/issues/15344

**Comment by madoublet** [comment]
From that thread... she had the exact same issue and fixed it using this process:

Hello again, sorry for the duplicate post, but I found a solution to the #85901 GRAPHQL error. Maybe this is helpful for others.

I updated gatsby-transformer-sharp to 2.2.1.
I removed sharp from the node_modules directory and re-installed it.
I checked my dependencies via npm list sharp, updated the packages that were listed, including gatsby-plugin-sharp and gatsby-transformer-sharp, and now gatsby build is successful and all deployments on Netlify are working as before.
Now everything is working fine again. 😆 Thanks again guys. Hope this helps you

**Comment by madoublet** [comment]
Looks like we have a green checkmark!  That is awesome.  Thank you!

**Comment by chriscoyier** [comment]
Made it!

**Pull request merged**
