### PR TITLE
Add Kentico Cloud 

### PR DESCRIPTION
**Pull request by Simply007**
I have added Kentico cloud as a representer of CMS.
I have also set the order of CMSs by its title.

### CODE REVIEW

**Comment by chriscoyier** [comment]
The sorting is pretty cool, but then this one page is sorted like that and none of the others are. Can you either remove that or add the sorting to all the other types?

**Comment by Simply007** [comment]
> The sorting is pretty cool, but then this one page is sorted like that and none of the others are. Can you either remove that or add the sorting to all the other types?

Sure, I can add it to all other types!

**Comment by Simply007** [comment]
Just one question, I am not able to install all the dependencies, beacuse there is a `package-lock.json` in the repo. To install all the modáules, I need to remove the file and install them. I would recommend to remove `package-lock.json` as well as `yarn.lock`.

**Comment by Simply007** [comment]
@chriscoyier - sorting implemented

**Comment by chriscoyier** [comment]
Much appreciated!

The design work for this project is still being done, so it might be a little bit before all this is live, but it'll be a big upgrade when it is!

**Comment by Simply007** [comment]
Hello @chriscoyier,

do you have some ETA about the site going live?

**Comment by chriscoyier** [comment]
Thursday should be

**Pull request merged**
