### PR TITLE
Add Scully

### PR DESCRIPTION
**Pull request by aaronfrost**
Add Scully to the project so that Angular developers looking for info about SSG can find a home.

### CODE REVIEW

**Comment by chriscoyier** [comment]
The copy is pretty marketing-heavy there with "wicked fast" and "enterprise ready" and such. Could it be updated to just explain what it is/does more straightforwardly?

**Comment by aaronfrost** [comment]
With regards to the "enterprise" I for sure can tone this down. 

I have removed the copy about wicked-fast, but would ask you to reconsider. Gatsby's tagline is Blazing fast, which I agree with. It is blazing fast. And on this site their copy uses that tagline. A few of our users started referring to Scully as wicked-fast. So we have adopted that tagline as well. We would like to use it here. Additionally, Gridsome's copy here also refers to the speed of apps by default. 

This is your gig. I don't want to pretend to understand your goals with this page. Without a full understanding, it does appear to me that referring to it as wicked-fast is on par with what Gatsby and Gridsome are describing. 

Thoughts?

**Comment by chriscoyier** [comment]
👍

**Comment by aaronfrost** [comment]
@chriscoyier you cool if I have another PR adding that back in, then?

**Comment by chriscoyier** [comment]
What I want is for the site to just use plain language to describe what things do. I see your point in that other SSGs are using marketing language too here rather than follow that guideline. If anything, a PR that removes marketing-esque language and just talks about what the thing does is more useful to me. For example, Gatsby could probably just say, "A React and GraphQL based static site generator with a broad set of plugins and adapters for different data sources."

**Comment by aaronfrost** [comment]
I see what you are saying. At the same time, I don't feel comfortable writing non-marketing-speak copy for the Gatsby and/or Gridsome. However, I would like Scully to be on the same ground as those projects on your page. 

I am willing to help out however you would like.

**Pull request merged**
