### PR TITLE
Create paperform.md

### PR DESCRIPTION
**Pull request by michelbaas**
Another great form service provider.

### CODE REVIEW

**Comment by chriscoyier** [comment]
Logo missing on this one.

**Comment by michelbaas** [comment]
Okay, sorry... I've added the missing logo's in PR #195.

**Comment by chriscoyier** [comment]
It's generally best to put the content and image together in a PR so that it can be previewed together, but I don't wanna nitpick too much here as I appreciate the help!

I'm just gonna merge 'em all in and we'll see how it turns out, if anything is weird we can mop it up.

**Comment by michelbaas** [comment]
Yes, you're right. Will do it like that next time.
Just checked it, and everything looks fine.

**Pull request merged**
