### PR TITLE
Update Forms “basin”

### PR DESCRIPTION
**Pull request by farleym**
Updated Basin logo and description to be more reflective of the current state of the product.

### CODE REVIEW

**Comment by chriscoyier** [comment]
The logo bombs out

Screen Shot 2020-08-06 at 3 32 28 PM

Maybe chuck it through an SVG optimizer?

**Comment by farleym** [comment]
Uploaded an optimized version to my branch. Let me know if that works.

**Comment by chriscoyier** [comment]
oh I think its because it needs to be in `src/images` instead of `src/img` sorry that's super dumb and I should fix someday.

**Comment by farleym** [comment]
Ok, anything else you need from me?

________________________________________________________
_______________________

*MATT FARLEY*
Designer

matt@pendeavor.com
www.mattfarley.ca
778.809.4577
@farleymatters <https://twitter.com/farleymatters>

**Pull request merged**
