### PR TITLE
feat: add open authoring

### PR DESCRIPTION
**Pull request by erezrokah**
Sorry opened by mistake here

### CODE REVIEW

**Comment by chriscoyier** [comment]
That's cool. Did your test work? I'm very interested in this open authoring feature.

**Comment by erezrokah** [comment]
Hey @chriscoyier, I just joined Netlify to work on the CMS. The PR was part of my tests and was meant to be opened on my forked repo :)

I can confirm that Open Authoring does work. There are a few steps to put it together as it doesn't support `git-gateway` backend at the moment:

1. Follow the steps [here](https://docs.netlify.com/visitor-access/oauth-provider-tokens/#setup-and-settings) to setup authentication with GitHub.
2. Use the latest beta: `yarn add netlify-cms-app@2.9.8-beta.4` (https://github.com/CSS-Tricks/serverless/pull/85/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21)
3. Update `config.yml` to use `github` backend, enable `open_authoring` and switch to `editorial_workflow` (https://github.com/CSS-Tricks/serverless/pull/85/files#diff-e36160419abb71f07eb8f74e9d3cc8bcR2)

I have the fork deployed [here](https://epic-fermat-7c8534.netlify.com/admin) if you want to try it before implementing.

One thing I have left to test is linking a document directly to the CMS (e.g. "click here to edit" button) and verifying the flow works correctly.

**Comment by erezrokah** [comment]
There's another PR [here](https://github.com/erezrokah/serverless/pull/6) for the "click here to edit button". The main thing was to make sure Gatsby and the CMS generate the same slug.

I can combine them into one PR and open it on this repo if you'd like

**Comment by chriscoyier** [comment]
Hey! That's hilarious I was JUST working on this after you've shown me open authoring is up and working. Mind making that same PR against this repo?

**Pull request closed without merging**
